# Generated by Django 5.2.5 on 2025-09-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'course')},
        ),
    ]
