# Generated by Django 5.2.5 on 2025-09-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_project_app', '0002_alter_payment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='created_by',
        ),
    ]
