# Generated by Django 5.2.5 on 2025-09-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo_project_app', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
    ]
